MDScreen:


MDScreen:
    name: "splash"
    MDFloatLayout:
        Image:
            source: "shield.jpg"
            size_hint: 0.9, 0.9
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
        
        MDLabel:
            text: "Splash!"
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            halign: 'center'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1
            font_size: "35sp"
            font_name: "3.ttf"

   
'''