########################################################################
## MAIN SCREEN
########################################################################
MDScreen:
    # Set screen name
    name: "MainScreen"  
    # Add box layout
    MDBoxLayout:
        padding: "10dp"
        # Add label
        MDLabel:
            text:'DADES ACTUALITZADES!!'
            font_style:'H6'
            # Horizontal text alignment
            halign: "center"
        